---
title: "Untitled"
output: html_document
date: "2024-06-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Packages, echo = FALSE, warning = FALSE, message = FALSE}
suppressMessages({
  memory.limit(size = 100000000)
  library(readxl)
  library(writexl)
  library(plyr)
  library(dplyr)
  library(data.table)
  library(zoo)
  library(shiny)
  library(shinydashboard)
  library(shinydashboardPlus)
  library(shinyWidgets)
  library(htmlwidgets)
  library(lubridate)
  library(tcltk)
  library(tidyverse)
  library(plotly)
  library(knitr)
  library(kableExtra)
  library(leaflet)
  library(grid)
  library(gridExtra)
  library(eeptools)
  library(ggQC)
  library(zipcodeR)
  library(utils)
  library(scales)
  library(chron)
  library(bupaR)
  library(shiny)
  library(DT)
  library(DiagrammeR)
  library(shinyalert)
  library(edeaR)
  library(processmapR)
  library(processmonitR)
  library(processanimateR)
  library(tidyr)
  library(lubridate)
  library(RColorBrewer)
  library(DiagrammeR)
  library(ggplot2)
  library(leaflet)
  library(readr)
  library(highcharter)
  library(ggforce) # for 'geom_arc_bar'
  library(packcircles) # for packed circle graph
  library(viridis)
  library(ggiraph)
  library(treemapify)
  library(treemap)
  library(broom)
  library(extrafont)
  library(tis) # for US holidays
  library(vroom)
  library(sjmisc)
  library(tools)
  library(here)
  library(shinyBS)
  library(shinyscreenshot)
  library(fasttime)
  library(shinycssloaders)
  library(feather)
  # library(zipcodeR)
  library(formattable)
  library(shinyjs)
  library(janitor)
  library(patchwork)
  library(flexdashboard)
  # library(tidyverse)
  # library(viridis)
  # library(hrbrthemes)
  # library(plotly)
  # install.packages("bsts")
  library(bsts)
  library(reactable)
  # install.packages("reactablefmtr")
  library(reactablefmtr)
  library(svDialogs)
  # library(openxlsx)
  library(flextable)
  library(officedown)
  library(officer)
  library(magrittr)
  library(webshot) 
  library(png)
  library(ggh4x)
  library(RODBC)
  library(DBI)
  library(odbc)
  library(dbplyr)
  library(pool)
  library(emojifont)
})

```


```{r Graph asthetics, echo = FALSE, warning = FALSE, message = FALSE}
### Color Functions for Graphs ============================================================
# Mount Sinai corporate colors "USE THIS TO ADD COLORS"
MountSinai_colors <- c(
  `dark purple`  = "#212070",
  `dark pink`    = "#d80b8c",
  `dark blue`    = "#00aeef",
  `dark grey`    = "#7f7f7f",
  `yellow`       = "#ffc000",
  `purple`       = "#7030a0",
  `med purple`   = "#5753d0",
  `med pink`     = "#f75dbe",
  `med blue`     = "#5cd3ff",
  `med grey`     = "#a5a7a5",
  `light purple` = "#c7c6ef",
  `light pink`   = "#fcc9e9",
  `light blue`   = "#c9f0ff",
  `light grey`   = "#dddedd"
  )
# Function to extract Mount Sinai colors as hex codes
# Use Character names of MountSinai_colors
MountSinai_cols <- function(...) {
  cols <- c(...)
  
  if (is.null(cols))
    return (MountSinai_colors)
  
  MountSinai_colors[cols]
}
# Color Function that can be used to call all colors is "MountSinai_cols()"
# Use in ggplot 
  #MountSinai_cols()       # will provide all colors and their hex codes in a table 
  #MountSinai_cols("pink") # will provide color name and the hex code for the pink color
# Create palettes 
MountSinai_palettes <- list(
  `all`   = MountSinai_cols("dark purple","dark pink","dark blue","dark grey",
                            "med purple","med pink","med blue","med grey", 
                            "light purple","light pink","light blue","light grey"),
  
  `main`  = MountSinai_cols("dark purple","dark pink","dark blue","dark grey"),
  
  `purple`  = MountSinai_cols("dark purple","med purple","light purple"),
  
  `pink`  = MountSinai_cols("dark pink","med pink","light pink"),
  
  `blue`  = MountSinai_cols("dark blue", "med blue", "light blue"),
  
  `grey`  = MountSinai_cols("dark grey", "med grey", "light grey"),
  
  `purpleGrey` = MountSinai_cols("dark purple", "dark grey"),
  
  `pinkBlue` = MountSinai_cols("dark pink", "dark blue")
  
)
# MountSinai_palettes
# Return function to interpolate a Mount Sinai color palette
# default value is the main palette, reverse = True will change the order
MountSinai_pal <- function(palette = "all", reverse = FALSE, ...) {
  pal <- MountSinai_palettes[[palette]]
  
  if (reverse) pal <- rev(pal)
  
  colorRampPalette(pal, ...)
}
# Scale Function for ggplot can be used instead of scale_color_manual
scale_color_MountSinai <- function(palette = "all", discrete = TRUE, reverse = FALSE, ...) {
  pal <- MountSinai_pal(palette = palette, reverse = reverse)
  
  if (discrete) {
    discrete_scale("colour", paste0("MountSinai_", palette), palette = pal, ...)
  } else {
    scale_color_gradientn(colours = pal(256), ...)
  }
}
# Scale Fill for ggplot insetead of scale_fill_manual 
scale_fill_MountSinai <- function(palette = "all", discrete = TRUE, reverse = FALSE, ...) {
  pal <- MountSinai_pal(palette = palette, reverse = reverse)
  if (discrete) {
    discrete_scale("fill", paste0("MountSinai_", palette), palette = pal, ...)
  } else {
    scale_fill_gradientn(colours = pal(256), ...)
  }
}
# Use in ggplot 
  # scale_color_MountSinai("main")
```


```{r Connect to Data Source, echo = FALSE, warning = FALSE, message = FALSE}

# Connection to Oracle DB ------------------------------------------------------
conn1 <- dbPool(drv = odbc(), dsn = "OAO Cloud DB SoYoun", timeout = 30)
conn2 <- dbConnect(odbc(), 
                  "Clarity_prod", 
                  uid = "kweons01" , 
                  pwd = "kweons01123$")

qpr_referrals_tbl <- tbl(conn1, "PROD_QPR_REFERRAL")
qpr_scehduling_tbl <- tbl(conn1, "PROD_QPR_SCHEDULING")
access_raw_tbl <- tbl(conn2, "MV_DM_PATIENT_ACCESS")

productivity_data <- read_excel(file.choose(), sheet = "Master Prod 2024")

```


```{r Productivity and Access Data Processing}

productivity_data_filtered <- productivity_data %>% 
  filter(!is.na(NPI)) %>%
  dplyr::select(`Master Dept`, Site, Department, Speciality, `CPSC Specialty`, Physician, NPI, 
                `2023 cFTE`, `Jan-Dec 2023 Collections`, `Jan-Dec 2023 wRVUs`, `2023 Calculate %`, `2023 Calculate %`,
                `2024 cFTE`, `Collections 2024 Annualized`, `Work RVUs 2024 Annualized`, `2024 Calculate %`) %>%
  mutate(NPI = as.character(NPI),
         `2023 Calculate %` = ifelse( `2023 Calculate %`>=1, 1,  `2023 Calculate %`),
         `2024 Calculate %` = ifelse( `2024 Calculate %`>=1, 1,  `2024 Calculate %`))


new_access <- qpr_scehduling_tbl %>% 
  filter(VISIT_GROUP_NUM == 4) %>%
  filter(year(APPT_MADE_DTTM) >= 2023) %>%
  mutate(wait_time = TO_DATE(CONTACT_DATE) - TO_DATE(APPT_MADE_DTTM)) %>%
  filter(wait_time >= 0) %>%
  mutate(wait_time_group = ifelse(wait_time >= 0 & wait_time <=7, "0-7",
                                  ifelse(wait_time >7 & wait_time <=14, "8-14",
                                         ifelse(wait_time >14 & wait_time <=30, "15-30", ">30")))) %>%
  collect() %>%
  filter(NPI %in% unique(productivity_data_filtered$NPI)) 

new_access_filered <- merge(new_access, productivity_data_filtered %>% dplyr::select(`Master Dept`, Site, Department, Speciality, `CPSC Specialty`, Physician, NPI),
                          by = "NPI",
                          all.x = TRUE)

```


```{r Productivity}

productivity_provider <- productivity_data_filtered %>%
  dplyr::select('Master Dept', Site, Department, Speciality, 'CPSC Specialty', Physician, NPI, 
                '2023 cFTE', '2023 Calculate %', 
                '2024 cFTE', '2024 Calculate %')

productivity_specialty <- productivity_data_filtered %>%
  mutate(weighted_productivity_2023 = `2023 cFTE`*`2023 Calculate %`,
         weighted_productivity_2024 = `2024 cFTE`*`2024 Calculate %`) %>%
  group_by(`Master Dept`, `CPSC Specialty`) %>%
  summarise(total_physicians_2023 = length(unique(NPI[`2023 cFTE`>=0.1])),
            total_physicians_2024 = length(unique(NPI[`2024 cFTE`>=0.1])),
            total_CFTE_2023 = sum(`2023 cFTE`[`2023 cFTE`>=0.1]),
            total_CFTE_2024 = sum(`2024 cFTE`[`2024 cFTE`>=0.1]),
            weighted_productivity_2023 = mean(weighted_productivity_2023),
            weighted_productivity_2024 = mean(weighted_productivity_2024))

productivity_master_dept <- productivity_data_filtered %>%
  mutate(weighted_productivity_2023 = `2023 cFTE`*`2023 Calculate %`,
         weighted_productivity_2024 = `2024 cFTE`*`2024 Calculate %`) %>%
  group_by(`Master Dept`) %>%
  summarise(total_physicians_2023 = length(unique(NPI[`2023 cFTE`>=0.1])),
            total_physicians_2024 = length(unique(NPI[`2024 cFTE`>=0.1])),
            total_CFTE_2023 = sum(`2023 cFTE`[`2023 cFTE`>=0.1]),
            total_CFTE_2024 = sum(`2024 cFTE`[`2024 cFTE`>=0.1]),
            weighted_productivity_2023 = mean(weighted_productivity_2023),
             weighted_productivity_2024 = mean(weighted_productivity_2024))
  

```



```{r Percent new patients scheduled within 14 days}

# By Provider ------------------------------------------------------------------
wait_time_provider <- new_access_filered %>%
  filter(NPI %in% unique(productivity_data_filtered$NPI)) %>%
  filter(as.Date(APPT_MADE_DTTM) < as.Date("2024-07-01")) %>% 
  mutate(appt_made_year = year(APPT_MADE_DTTM)) %>%
  group_by(`Master Dept`, `CPSC Specialty`, Physician, NPI, PROV_NAME_WID, appt_made_year) %>%
  summarise(med_wait_time = median(wait_time, na.rm = T)) %>%
  mutate(appt_made_year = paste0(appt_made_year, "_med_wait_time")) %>%
  pivot_wider(names_from = appt_made_year, 
              values_from = med_wait_time, 
              values_fill = NA)


perc_new_fourteen_provider <- new_access_filered %>%
  filter(NPI %in% unique(productivity_data_filtered$NPI)) %>%
  filter(as.Date(APPT_MADE_DTTM) < as.Date("2024-07-01")) %>% 
  mutate(appt_made_year = year(APPT_MADE_DTTM)) %>%
  group_by(`Master Dept`, `CPSC Specialty`, Physician, NPI, PROV_NAME_WID, appt_made_year, wait_time_group) %>%
  summarise(total = n()) %>%
  pivot_wider(names_from = "wait_time_group",
              values_from = "total",
              values_fill = 0) %>%
  mutate(perc_within_fourteen = (`0-7` + `8-14`)/(`0-7` + `8-14` + `15-30` + `>30`)) %>%
  dplyr::select(`Master Dept`, `CPSC Specialty`, Physician, NPI, PROV_NAME_WID, appt_made_year, perc_within_fourteen) %>%
   mutate(appt_made_year = paste0(appt_made_year, "_perc_within_fourteen")) %>%
  pivot_wider(names_from = appt_made_year,
              values_from = perc_within_fourteen,
              values_fill = 0)



# By Department ----------------------------------------------------------------
wait_time_master_dept <- new_access_filered %>%
  filter(NPI %in% unique(productivity_data_filtered$NPI)) %>%
  filter(as.Date(APPT_MADE_DTTM) < as.Date("2024-07-01")) %>% 
  mutate(appt_made_year = year(APPT_MADE_DTTM)) %>%
  group_by(`Master Dept`, appt_made_year) %>%
  summarise(med_wait_time = median(wait_time, na.rm = T))   %>%
  mutate(appt_made_year = paste0(appt_made_year, "_med_wait_time")) %>%
  pivot_wider(names_from = appt_made_year, 
              values_from = med_wait_time, 
              values_fill = NA)



perc_new_fourteen_master_dept <- new_access_filered %>%
  filter(NPI %in% unique(productivity_data_filtered$NPI)) %>%
  filter(as.Date(APPT_MADE_DTTM) < as.Date("2024-07-01")) %>% 
  mutate(appt_made_year = year(APPT_MADE_DTTM)) %>%
  group_by(`Master Dept`, appt_made_year, wait_time_group) %>%
  summarise(total = n()) %>%
  pivot_wider(names_from = "wait_time_group",
              values_from = "total",
              values_fill = 0) %>%
  mutate(perc_within_fourteen = (`0-7` + `8-14`)/(`0-7` + `8-14` + `15-30` + `>30`)) %>%
  dplyr::select(`Master Dept`,appt_made_year, perc_within_fourteen) %>%
   mutate(appt_made_year = paste0(appt_made_year, "_perc_within_fourteen")) %>%
  pivot_wider(names_from = appt_made_year,
              values_from = perc_within_fourteen,
              values_fill = 0)


# By Specialty ----------------------------------------------------------------
wait_time_specialty <- new_access_filered %>%
  filter(NPI %in% unique(productivity_data_filtered$NPI)) %>%
  filter(as.Date(APPT_MADE_DTTM) < as.Date("2024-07-01")) %>% 
  mutate(appt_made_year = year(APPT_MADE_DTTM)) %>%
  group_by(`Master Dept`, `CPSC Specialty`, appt_made_year) %>%
  summarise(med_wait_time = median(wait_time, na.rm = T)) %>%
  mutate(appt_made_year = paste0(appt_made_year, "_med_wait_time")) %>%
  pivot_wider(names_from = appt_made_year, 
              values_from = med_wait_time, 
              values_fill = NA)



perc_new_fourteen_specialty <- new_access_filered %>%
  filter(NPI %in% unique(productivity_data_filtered$NPI)) %>%
  filter(as.Date(APPT_MADE_DTTM) < as.Date("2024-07-01")) %>% 
  mutate(appt_made_year = year(APPT_MADE_DTTM)) %>%
  group_by(`Master Dept`, `CPSC Specialty`, appt_made_year, wait_time_group) %>%
  summarise(total = n()) %>%
  pivot_wider(names_from = "wait_time_group",
              values_from = "total",
              values_fill = 0) %>%
  mutate(perc_within_fourteen = (`0-7` + `8-14`)/(`0-7` + `8-14` + `15-30` + `>30`)) %>%
  dplyr::select(`Master Dept`, `CPSC Specialty`,appt_made_year, perc_within_fourteen) %>%
   mutate(appt_made_year = paste0(appt_made_year, "_perc_within_fourteen")) %>%
  pivot_wider(names_from = appt_made_year,
              values_from = perc_within_fourteen,
              values_fill = 0)


```


```{r Merge Provider and Department Tables}

access_productivity_merged_provider <- Reduce(function(...) merge(..., all=TRUE), list(productivity_provider, wait_time_provider, perc_new_fourteen_provider))
access_productivity_merged_specialty <- Reduce(function(...) merge(..., all=TRUE), list(productivity_specialty, wait_time_specialty, perc_new_fourteen_specialty))
access_productivity_merged_master_dept <- Reduce(function(...) merge(..., all=TRUE), list(productivity_master_dept, wait_time_master_dept, perc_new_fourteen_master_dept))


require(openxlsx)
write.xlsx(access_productivity_merged_provider, "access_productivity_merged_provider.xlsx")
write.xlsx(access_productivity_merged_specialty, "access_productivity_merged_specialty.xlsx")
write.xlsx(access_productivity_merged_master_dept, "access_productivity_merged_master_dept.xlsx")

```

